name: Enhanced Poisson Image Editor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r streamlit_requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v || echo "No tests found"
    
    - name: Test Streamlit app startup
      run: |
        timeout 30s streamlit run app.py --server.headless=true --server.port=8501 &
        sleep 10
        curl -f http://localhost:8501 || exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deploy to Streamlit Cloud by connecting your GitHub repository"
        echo "Visit: https://share.streamlit.io/"
    
    - name: Build Docker image
      run: |
        docker build -t poisson-editor:latest .
        echo "Docker image built successfully"
